admin = User.create(username: "admin", password: "nkv674zunyd9nbtx", account_type: "admin")
user_l = User.create(username: "catlady", password: "abc123", account_type: "user")
user_m = User.create(username: "catman", password: "abc123", account_type: "user")

#  "title", "genre", "year", "summary", "user_id"

Movie.create(title: "A Single Man", genre: "Drama", year: "2009", summary: "An English professor, one year after the sudden death of his boyfriend, is unable to cope with his typical days in 1960s Los Angeles.", user_id: 1)
Movie.create(title: "Love, Simon", genre: "Romcom", year: "2018", summary: "Everyone deserves a great love story, but for 17-year-old Simon, it's a bit complicated.", user_id: 2)
Movie.create(title: "Some Like It Hot", genre: "Comedy", year: "1959", summary: "After two male musicians witness a mob hit, they flee the state in an all-female band disguised as women, but further complications set in.", user_id: 3)

Comment.create(content: "George and Jim are in an explicit relationship for 17 years before Jim unexpectidly dies in a car crash. During the movie, set 8 months after Jim's death, George is clearly still in mourning but shows interest in other men. First Carlos, who he meets outside a liquor store and is emplied to be a sex worker (George gives him money but declines to actually pick him up). There is also Kenny, one of George's students, who shows clear interest in him. George is clearly conflicted about this. The two share some drinks and go skinny dipping but no further than that.", movie_id: 1 , user_id: 1)
Comment.create(content: "The movie is based on the novel by Christopher Isherwood. Isherwood was in a relationship with artist Don Bachardy for many decades and the novel seems to mirror some aspects of their relationship (Isherwood was older than Bachardy, similarly to the age gap between George and Jim).", movie_id: 1, user_id: 1)
Comment.create(content: "George talks about having sex with women (or at least one woman, his best friend Charly) and tells Jim that while he might sleep with women he 'Falls in love with men'. Jim admits that he is only interested in men and has never slept with a woman.", movie_id: 1, user_id: 2)
Comment.create(content: "Total of 3 gay characters; the titular Simon, the mystery boy he's emailing with, and one other student at their school. Warning for forced outing of a queer character, which is never fully resolved.", movie_id: 2, user_id: 2)
Comment.create(content: "For a school that apparenlty isn't very gay they do the musical 'Cabaret' with, presumably, an entire straight cast. In high school.", movie_id: 2, user_id: 3)
Comment.create(content: "Simon Spier keeps a huge secret from his family, his friends and all of his classmates: he's gay. When that secret is threatened, Simon must face everyone and come to terms with his identity.", movie_id: 2, user_id: 2)
Comment.create(content: "After two Chicago musicians, Joe and Jerry, witness the the St. Valentine's Day massacre, they want to get out of town and get away from the gangster responsible, Spats Colombo. They're desperate to get a gig out of town but the only job they know of is in an all-girl band heading to Florida. They show up at the train station as Josephine and Daphne, the replacement saxophone and bass players. They certainly enjoy being around the girls, especially Sugar Kane Kowalczyk who sings and plays the ukulele. Joe in particular sets out to woo her while Jerry/Daphne is wooed by a millionaire, Osgood Fielding III. Mayhem ensues as the two men try to keep their true identities hidden and Spats Colombo and his crew show up for a meeting with several other crime lords.", movie_id: 3, user_id: 3)
Comment.create(content: "Joe goes back and forth between forming a friendship with Sugar as his female persona Joesephine and trying to woo her with another made up persona of the heir of a rich oil tycoon, Junior. Jerry meanwhile, as Daphne, is being wooed by a rich older man named Osgood.", movie_id: 3, user_id: 2)
Comment.create(content: "At the end of the film, Osgood helps Joe, Jerry, and Sugar escape. Jerry comes clean that he isn't a woman and Osgood is unphased, saying he still intends to marry him and that 'Nobody is perfect'.", movie_id: 3, user_id: 1)